### ISSUE TITLE
switch.ftl: missed Facebook as placeable.

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/www-l10n#15]
@alexgibson when tou migrate the next batch of files, let's update the file to include Facebook: https://github.com/mozilla-l10n/www-l10n/blob/843002b1c19fa341d8d7c05635c1059a86f5dedf/en/firefox/switch.ftl#L20

**Comment by flodolo** [comment]
@peiying2 
You can't update existing strings without new IDs, especially when doing changes that will cause a warning to show up for all locales.

I'm starting to think this is what caused https://bugzilla.mozilla.org/show_bug.cgi?id=1648377

**Comment by peiying2** [comment]
https://github.com/mozilla/bedrock/issues/9056
