### ISSUE TITLE
Add a webhook to this repo for bedrock automation

### ISSUE THREAD

**Issue by pmac** [mozilla-l10n/www-l10n#20]
Go to: Settings -> Webhooks -> [Add webhook]. 

* **Payload URL**: https://gitlab.com/api/v4/projects/10706092/ref/master/trigger/pipeline?token=TOKEN (I'll send you the token separately)
* **Content type**: default is fine
* **Secret**: leave blank
* **Which events would you like to trigger this webhook?**: Just the push event
* **Active**: checked

**Comment by Pike** [comment]
Done.
