### ISSUE TITLE
VPN landing page (es-ES) unclosed link

### ISSUE THREAD

**Issue by alexgibson** [mozilla-l10n/www-l10n#210]
There's an unclosed link in the es-ES VPN landing page that's breaking the page layout:

![image](https://user-images.githubusercontent.com/400117/122949156-58d53680-d373-11eb-9866-17837f733a90.png)

https://www.mozilla.org/es-ES/products/vpn/

https://github.com/mozilla-l10n/www-l10n/blob/master/es-ES/products/vpn/landing.ftl#L24

**Comment by peiying2** [comment]
Thank you for catching it. I fixed it in Pontoon. Will check on staging and prod servers soon  to confirm the fix.

**Comment by peiying2** [comment]
Fix confirmed!
