### ISSUE TITLE
Staging URL for an VPN page is incorrect

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/www-l10n#216]
- **File**: en/products/vpn/more/when-to-use-a-vpn.ftl
- **Current**: https://www-dev.allizom.org/products/vpn/more/when-to-use/
- **Expected**: https://www-dev.allizom.org/en-US/products/vpn/more/when-to-use-a-vpn/

**Comment by peiying2** [comment]
@craigcook the URL embedded in the file is incorrect. Let's fix it when you get a chance.

**Comment by craigcook** [comment]
Oops, copy-paste error. I'll get a fix in.
