### ISSUE TITLE
Shared string in multiple context should turn into separate strings

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/www-l10n#225]
This string [30-day money-back guarantee](https://github.com/mozilla-l10n/www-l10n/blob/3a46e0cec41e2454d89719aa9b0009e9735f7e20/en/products/vpn/shared.ftl#L19) is used multiple times on [this page](https://www-dev.allizom.org/en-US/products/vpn/). For some languages, the translation is different depending on context. Let's break it up into types:
- Standalone string
- One of the bullet items

When a fix is added, let's make sure the string IDs and comments provide good context so it is clear which string is used where.

**Comment by peiying2** [comment]
@craigcook feel free to triage the issue to the right person. Thank you!

**Comment by craigcook** [comment]
cc: @alexgibson

**Comment by alexgibson** [comment]
@peiying2 thanks, I'll see if we can get this fixed 👍

**Comment by peiying2** [comment]
Maybe we keep this string by adding a comment where it's used. And the other is  more specific in the  string ID and add a comment. This way we don't lose the work of one string due to ID change.

**Comment by alexgibson** [comment]
PR for the change: https://github.com/mozilla/bedrock/pull/10417

**Comment by peiying2** [comment]
Looks good!
