### ISSUE TITLE
Some incorrect currencies for fundraising banner

### ISSUE THREAD

**Issue by alexgibson** [mozilla-l10n/www-l10n#254]
I'm working on the MOFO fundraising banner for 2021 and I noticed some locales are using incorrect / mismatching currencies.

You can see each corresponding value by clicking "Donate" and viewing the next page.

- ~https://www-dev.allizom.org/cy/ shows `$` instead of `£`.~
- ~https://www-dev.allizom.org/el/ shows `$` instead of `€`.~
- https://www-dev.allizom.org/ja/ shows `$` instead of `￥`.
- ~https://www-dev.allizom.org/nn-NO/ shows `NOK` instead of `kr`.~
- ~https://www-dev.allizom.org/ru/ shows `$` instead of `₽`.~
- ~https://www-dev.allizom.org/sv-SE/ shows `SEK` instead of `kr`.~

Here's the string in question: https://github.com/mozilla/bedrock/blob/master/l10n/en/banners/fundraising.ftl#L13-L16

**Comment by alexgibson** [comment]
@peiying2 can you please try and work with communities to get these fixed?

Please let me know if I can be of any help or answer questions. Thanks

**Comment by alexgibson** [comment]
@peiying2 looks like hi-IN is also incorrect https://www-dev.allizom.org/hi-IN/

**Comment by peiying2** [comment]
These two are on Smartling and I had a hard time locating the string. I sent a message to the community on this but most of the people read it had correct configuration so I fixed those in Pontoon. I hope to resolve these two soon.

**Comment by peiying2** [comment]
I found them and fixed them - their platform must be down yesterday.  Let me know if you find more.

**Comment by peiying2** [comment]
I can confirm that ja, hi-IN are fixed.

**Comment by alexgibson** [comment]
Thanks @peiying2, closing!
