### ISSUE TITLE
Need to add entry to pontoon.toml for welcome/13.ftl

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/www-l10n#263]
en/firefox/welcome/13.ftl is not shown in Pontoon. Need to add an entry to the config file pontoon.toml. https://github.com/mozilla-l10n/www-l10n/blob/master/configs/pontoon.toml

**Comment by craigcook** [comment]
This page is only going to Smartling for a subset of locales, but I'm not 100% clear on the workflow. I thought the rules in https://github.com/mozilla/bedrock/blob/master/l10n/configs/vendor.toml meant ALL Fluent files go to Smartling for those locales without needing to add them individually. Is that wrong?

**Comment by craigcook** [comment]
Well looking at vendor.toml I don't even see all the target locales for this page in there, so maybe it does have to go to Pontoon. I'm not even sure what Smartling does at this point.

**Comment by peiying2** [comment]
The vendor got the page, just not Pontoon. We don't configure vendor.toml now. We translate all the languages for all the pages pushing to Smartling.

**Comment by craigcook** [comment]
Fixed in https://github.com/mozilla/bedrock/commit/447768c7c5b34a29f26769d22825a35d05abe015.

I thought the set of locales we were targeting were all covered by Smartling, but I was wrong.

**Comment by craigcook** [comment]
https://github.com/mozilla-l10n/www-l10n/pull/264
