### ISSUE TITLE
Error in French translation of a string on the firefox/new page

### ISSUE THREAD

**Issue by pmac** [mozilla-l10n/www-l10n#266]
A user reported that the line on https://www.mozilla.org/fr/firefox/new/, "Faites ce que vous avez à faire en ligne.
navigateur Firefox ne vous épie jamais." should be "Faites ce que vous avez à faire en ligne.
**Le** navigateur Firefox ne vous épie jamais." The "Le" should be added to the beginning of the 2nd sentence in the tag line. 

I believe the string ID is `firefox-desktop-download-do-what-you-do` which is here: https://github.com/mozilla-l10n/www-l10n/blob/e5f02560541936196600b153bb6e46432f8a6d9a/fr/firefox/new/desktop.ftl#L22

I don't personally speak French, I'm just reporting what was reported to me. 

cc @peiying2

**Comment by beurdouche** [comment]
I do speak french natively and can confirm. The sentence should be "Le navigateur Firefox ne vous épie jamais".
It looks like the translation might have worked correctly if the original sentence had been:
"The Firefox browser isn't watching" or "Firefox isn't watching"

**Comment by peiying2** [comment]
I fixed it on Smartling: https://ti.smartling.com/app/b81dc4cef?locale=fr-FR&start=0&stringIds=cc875a9993ee7d5bc7a03a17b4d9eb86&stringIdsOrdering=true&workflowStepUids=0611996c8201, but somehow it is not syncing up with the repo.

**Comment by peiying2** [comment]
Confirm that the issue is fixed. The cron job was off earlier.

**Comment by pmac** [comment]
Thanks!
