### ISSUE TITLE
IA: Two fixes needed for /ia/mozorg/about/this-site.ftl

### ISSUE THREAD

**Issue by stevejalim** [mozilla-l10n/www-l10n#302]
Spotted by https://github.com/mozmeao/www-site-checker

* https://github.com/mozilla-l10n/www-l10n/blob/master/ia/mozorg/about/this-site.ftl#L35 is talking about Fluent and it should be talking about Protocol. Note that the variable being used will also need updating because `fluent` isn't available for this string
* https://github.com/mozilla-l10n/www-l10n/blob/master/ia/mozorg/about/this-site.ftl#L20 uses `$libro` when the variable is called `$book`

**Comment by stevejalim** [comment]
@flodolo Would you mind steering this ticket from here, please? It's not blocking anything, but good to get fixed, naturally!

**Comment by flodolo** [comment]
These should really be on @peiying2, since it's her project.

I think she's going through errors at the moment, but there are quite a few, so I'm not sure it's worth filing individual issues (unless it breaks automation on your side, in which case she should prioritize some).

**Comment by peiying2** [comment]
We can close the issue now as the legacy issues flagged were fixed.
