### ISSUE TITLE
Link placeholders mixed up in `de/` & `fr/footer-refresh`

### ISSUE THREAD

**Issue by janbrasna** [mozilla-l10n/www-l10n#455]
Reported in bedrock issue: 
- https://github.com/mozilla/bedrock/issues/15593

Confirmed:
https://github.com/mozilla-l10n/www-l10n/blob/ffc745061b374d3a25d90d2409b1dda8ae366455/fr/footer-refresh.ftl#L35

(referencing `$moco_link }»{ -brand-name-mozilla-foundation` while `$mofo_link }»{ -brand-name-mozilla-corporation`…)

**Comment by janbrasna** [comment]
The same is in German:

https://github.com/mozilla-l10n/www-l10n/blob/ffc745061b374d3a25d90d2409b1dda8ae366455/de/footer-refresh.ftl#L35

**Comment by janbrasna** [comment]
The same issue is in `pa-IN` however that one doesn't come from Smartling, right?:
https://github.com/mozilla-l10n/www-l10n/blob/7577f9c3b981c7a7c0078342bc4388a5fe39cdb0/pa-IN/footer.ftl#L21

Is it OK to change all three right here in git, or those from Pontoon should be corrected in Pontoon, and those coming from vendor sync should be changed elsewhere? Or the sync is both ways, so changes made directly here wouldn't break anything?

**Comment by peiying2** [comment]
@janbrasna please do. These are vendor supported locales: https://github.com/mozilla/bedrock/blob/main/l10n/configs/vendor.toml

**Comment by peiying2** [comment]
@janbrasna vendor supported locales must be fixed in the vendor platform, otherwise the next update will revert the change here. 

For the community supported locales, you can change it here or in Pontoon. Is the issue widespread? Is there a more automated way to identify all the ones with issue and change them in one go vs. manual?

**Comment by janbrasna** [comment]
In that case could you please facilitate the DE & FR fixes upstream, @peiying2?

I'll PR the other only two in pa-IN here, that is the only occurrence (I just checked).

**Comment by peiying2** [comment]
This was fixed through the vendor's platform for German and French.

**Comment by janbrasna** [comment]
This has unfortunately been changed the other way around — now it says:
- "Besuche die MOCO, die Not-For-Profit Muttergesellschaft der MOFO"
meaning
- "Visit MOCO, the not-for-profit parent company of MOFO"

**Comment by peiying2** [comment]
Take a look of both French and German to see if they appear correctly.

**Comment by janbrasna** [comment]
@peiying2 I unfortunately don't understand French enough to infer the correct relation between the words, but it seems German and French are done in tandem so I'm taking the hint from German (that I can understand):

1. `footer.ftl` was correct, so the change in 2001a84 should have not been made, is wrong, and introduces the same bug as was reported here above for `footer-refresh.ftl` — therefore should be reverted.
2. `footer-refresh.ftl` that is currently published went through ef2a1dc that has the issue I mentioned above (in an attempt to fix the issue, the relation of the parent foundation and the subsidiary got reversed — meaning instead of swapping the link placeholders, the brand got swapped instead, making the ownership the other way around) and is currently at 44ae9ec that basically reverted the brands back to where it was yesterday. So the relation is not wrong anymore, but the links still are. Therefore a fix is still necessary, swapping the link placeholders like this: 75ce6ec

**Comment by peiying2** [comment]
@janbrasna thank you for explaining it. I believe I fixed all four files in both languages. In the vendor's platform, the URLs and Fluent term shows as coded like {0} or {1}, so it's difficult to see the connection between the two and they were switched around to accommodate the language flow.

**Comment by janbrasna** [comment]
These look great now, thank you so much for taking care of it personally. I can confirm these all now align with what bedrock had pre-refresh, so assuming to be correct. (Can personally confirm German in prod is OK and had the reporter confirm the same resolved for French to double check.)
